//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlpineBitsTestClient
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rules2017
    {
        public long rule_id { get; set; }
        public string rule_context { get; set; }
        public string rule_target_applicateion { get; set; }
        public string rule_chapter_number { get; set; }
        public string rule_chapter_rule_number { get; set; }
        public string rule_parent_rule_number { get; set; }
        public string rule_chapter_desc { get; set; }
        public string rule_page_number { get; set; }
        public string rule_text { get; set; }
        public string rule_type { get; set; }
        public string rule_scope { get; set; }
        public string call_action { get; set; }
        public string call_param { get; set; }
        public string audit_result_text { get; set; }
        public Nullable<long> audit_result { get; set; }
        public string audit_date { get; set; }
    }
}
